### ISSUE TITLE
Speed control

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafanimate#1]
People asked us about how to control the recording speed of _grafanimate_:
> Is it possible to adjust the "frameduration" with which a snapshot is present at the end of the video somewhere?

**Comment by amotl** [comment]
While it's not a command line parameter yet, adjusting the `-framerate` parameter to _ffmpeg_ might help, see https://github.com/daq-tools/grafanimate/blob/c35b06cc4d7b9469d67083161c82c89b553cecf6/grafanimate/postprocessing.py#L22.

**Comment by maurerle** [comment]
This is exposed to the users through the `video-framerate` param.

See https://github.com/grafana-toolbox/grafanimate?tab=readme-ov-file#usage-in-containers

So I think that we can close this :)
