### ISSUE TITLE
Event handling broken since Grafana 8 introduced React

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafanimate#17]
Hi there,

since Grafana 8 introduced React, `grafanimate` is having a hard time to properly synchronize with the frontend in order to capture frames efficiently. More information can be found at [^1].

With kind regards,
Andreas.

[^1]: https://community.grafana.com/t/how-to-add-event-handler-in-grafana-8-react-panel-plugins/58668/4.

**Comment by amotl** [comment]
@IntermittentNRG apparently found a solution for newer versions of Grafana, and submitted GH-19, reflecting that. Thanks a stack!

**Comment by maurerle** [comment]
this was fixed in #32

**Comment by amotl** [comment]
Thanks for your excellent contributions, @maurerle.

/cc @wetterfrosch
