### ISSUE TITLE
Debian Firefox ESR not used

### ISSUE THREAD

**Issue by gogglespisano** [grafana-toolbox/grafanimate#18]
On Debian, Firefox ESR is normally installed.  In /usr/bin/ there is "firefox" and "firefox-esr".  When find_firefox() sees "firefox", it tries to use it and fails.  It needs to find and try "firefox-esr" first.

The follow change in marionette.py line 111 fixes the problem, and should still work for a regular firefox installation.

    def find_firefox(cls):
        candidates = where.where("firefox-esr")
        candidates += where.where("firefox")
        candidates += [
            "/Applications/Firefox.app/Contents/MacOS/firefox-bin"
        ]

**Comment by amotl** [comment]
Dear Stuart,

apologies for the late reply. We just added f78451198a2fa, after the same problem tripped @intermittentnrg when running grafanimate in Docker.

With kind regards,
Andreas.

**Comment by maurerle** [comment]
could you please release this to pypi as well?

**Comment by amotl** [comment]
Dear Florian,

would you like to see a release based on the code in current `main`, or shall we include your improvements before running another release?

- GH-30

With kind regards,
Andreas.

**Comment by intermittentnrg** [comment]
Maybe path to firefox should be a config option, keeping current behaviour as default.

**Comment by maurerle** [comment]
I think the current behavior of firefox detection worked fine on my side using debian esr
So we can close this issue from my side, as it seems that everythung works :)

**Comment by amotl** [comment]
Hi. I think extending the list of candidates to provide good [DWIM](https://en.wikipedia.org/wiki/DWIM) is way to go. On the other hand, I also believe a configuration option that takes precedence makes sense, to be able to point grafanimate to a dedicated Firefox, for example if you have multiple ones on your machine.

**Comment by amotl** [comment]
There is a little improvement to this now.

- GH-44

**Comment by amotl** [comment]
The improvement referenced above has been released with grafanimate 0.8.1, so I guess it will be safe to close this ticket. Thanks again, @gogglespisano and @intermittentnrg.
