### ISSUE TITLE
Timing problem when rendering specific dashboard

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafanimate#2]
When trying to render https://weather.hiveeyes.org/grafana/d/of6c9qlmk/uba-ldi-dwd-studio-dev, it feels like _grafanimate_ has some problem taking the snapshot at exactly the time after data loading has finished, see screenshot:

![image](https://user-images.githubusercontent.com/453543/52247218-53cdd480-28e9-11e9-88f0-26d0940d531d.png)

**Comment by maurerle** [comment]
I don't know about this issue specifically, as the grafana on https://weather.hiveeyes.org/grafana/d/of6c9qlmk/uba-ldi-dwd-studio-dev?orgId=1 is still running grafana 9 - but I think that this is solved for updated instances in  #32

**Comment by amotl** [comment]
Thanks. Because most recent grafanimate does not support older instances of Grafana any longer, I guess it will be safe to close this issue.
