### ISSUE TITLE
Optimize size and rebuild behavior of OCI image

### ISSUE THREAD

**Issue by amotl** [grafana-toolbox/grafanimate#25]
### Optimize image size

> Each command creates a layer in the docker image that contains the changes to the previous layer.
> All files are still left in the previous layer and space is saved in the image.
> To fix this, run `apt install`, `pip install`, and `apt remove` in a single `RUN` command so that files are not kept in hidden layers.

_Originally posted by @intermittentnrg in https://github.com/panodata/grafanimate/pull/24#discussion_r1362021795_

### Optimize rebuild behavior

> Currently, `pip install` is copying all python files from `/src` to elsewhere so it now needs to run and will install dependencies when any .py/application file is changed. Changes in Python should not re-run `pip` etc., only if `setup.py` (or `README.rst`) were changed.

_Originally posted by @intermittentnrg in https://github.com/panodata/grafanimate/pull/24#discussion_r1362083086 and https://github.com/panodata/grafanimate/pull/24#discussion_r1362073190_

**Comment by amotl** [comment]
Dear @intermittentnrg,

thank you for your attention to detail. I am currently travelling, but I will be happy to address this topics on the next iteration in one way or another.

With kind regards,
Andreas.

**Comment by maurerle** [comment]
I think this is fine with the changes in #31 - I am quite impressed how fast building is with the `--mount=type=cache` part :)

How can we enable the docker registry again?
Probably it makes sense to turn of the regular cron job in github actions, to only build on new releases..?

**Comment by amotl** [comment]
OCI building and publishing has been fixed with GH-33.
