### ISSUE TITLE
Specify delta and duration from scenarios.py

### ISSUE THREAD

**Issue by intermittentnrg** [grafana-toolbox/grafanimate#27]
Hello again! My use of this tool is intermittent (pun intended). It takes time for data to accumulate, so I only make new videos every few months.

I would like to provide custom delta/interval, i.e. duration that is skipped forward per frame.
I just want to provide my own value to have exact control.

The delta is calculated  from the `every` parameter in scenarios.py  in `get_freq_delta`.
https://github.com/panodata/grafanimate/blob/main/grafanimate/timeutil.py#L40

Maybe just skip the call to get_freq_delta is a delta is provided from scenarios.py? https://github.com/panodata/grafanimate/blob/main/grafanimate/model.py#L48

**Comment by amotl** [comment]
Thank you very much. I merged GH-28 right away, and also invited you to this repository as a collaborator with "maintenance" permissions.
